@echo off
REM ---------------------------------------------------------------
REM  Talk to my files
REM  Double-click to chat with the AI about the files in this
REM  folder. No coding knowledge needed.
REM  (Generated by the agent-friendly-knowledge-docs skill.)
REM ---------------------------------------------------------------

REM Use UTF-8 for accents and emoji (best effort on old consoles).
chcp 65001 >nul 2>nul

REM Enter the folder this file lives in (the "mother" folder).
cd /d "%~dp0"

REM Clear the screen so no scary technical text shows.
cls

echo(
echo    Hi! 👋
echo(
echo    I'm the AI that knows the files in this folder.
echo    Ask me anything about them.
echo(
echo    For example:
echo    - "what's in this folder?"
echo    - "summarize the proposal for client X"
echo    - "which is the latest version of the model?"
echo(
echo    --------------------------------------------------
echo(

REM Python powers the "what changed" check below. Offer to install it if missing;
REM whatever happens, continue to the chat.
set "PY_CMD="
where python  >nul 2>nul && set "PY_CMD=python"
if not defined PY_CMD ( where python3 >nul 2>nul && set "PY_CMD=python3" )
if defined PY_CMD goto tpy_ok
echo    Python isn't installed -- it powers the automatic change-tracking.
choice /c yn /n /m "   Install it now? [y] yes / [n] skip: "
if errorlevel 2 goto tpy_skip
where winget >nul 2>nul
if errorlevel 1 (
  echo    winget isn't available -- opening the Python download page...
  start "" "https://www.python.org/downloads/"
  goto tpy_ok
)
echo    Installing Python via winget...
winget install -e --id Python.Python.3.13 --accept-source-agreements --accept-package-agreements
if errorlevel 1 ( start "" "https://www.python.org/downloads/" & goto tpy_ok )
for /f "usebackq delims=" %%P in (`powershell -NoProfile -Command "[Environment]::GetEnvironmentVariable('Path','Machine') + ';' + [Environment]::GetEnvironmentVariable('Path','User')"`) do set "PATH=%PATH%;%%P"
where python  >nul 2>nul && set "PY_CMD=python"
if not defined PY_CMD ( where python3 >nul 2>nul && set "PY_CMD=python3" )
echo    Done.
goto tpy_ok
:tpy_skip
echo    OK -- chatting now; tracking turns on once Python is installed.
echo(
:tpy_ok

REM Forcing gate (works for Claude Code AND Codex): if the files changed since the
REM docs were last updated, nudge the user to catch up first.
if defined PY_CMD if exist ".claude\hooks\snapshot.py" (
  %PY_CMD% ".claude\hooks\snapshot.py" check . >nul 2>nul
  if errorlevel 3 (
    echo    [!] Some files changed since last time.
    echo        Before anything else, ask me: "what changed?" -- I'll update the notes.
    echo(
  )
)

REM Which assistants are installed?
set HAVE_CLAUDE=0
where claude >nul 2>nul && set HAVE_CLAUDE=1
set HAVE_CODEX=0
where codex >nul 2>nul && set HAVE_CODEX=1

set "S1=not installed, I can set it up"
if "%HAVE_CLAUDE%"=="1" set "S1=installed"
set "S2=not installed, I can set it up"
if "%HAVE_CODEX%"=="1" set "S2=installed"

REM Always show the picker, marking what's installed.
echo    Which assistant do you want to use?
echo(
echo    [1] Claude Code   %S1%
echo    [2] Codex         %S2%
echo(
choice /c 12 /n /m "   Type 1 or 2: "
if errorlevel 2 goto sel_codex

:sel_claude
if "%HAVE_CLAUDE%"=="1" ( claude & goto done )
where wsl >nul 2>nul && wsl -e sh -lc "command -v claude >/dev/null 2>&1" && ( wsl claude & goto done )
set "DOCS=https://code.claude.com/docs/en/quickstart"
echo(
echo    Claude Code isn't installed yet. I can set it up for you.
choice /c yn /n /m "   Install it now? [y] yes  /  [n] just show me the guide: "
if errorlevel 2 goto guide
echo(
echo    Installing Claude Code... this can take a minute.
echo(
powershell -NoProfile -ExecutionPolicy Bypass -Command "irm https://claude.ai/install.ps1 | iex"
goto installed_reopen

:sel_codex
if "%HAVE_CODEX%"=="1" ( codex & goto done )
set "DOCS=https://learn.chatgpt.com/docs/codex/cli"
echo(
echo    Codex isn't installed yet. I can set it up for you.
choice /c yn /n /m "   Install it now? [y] yes  /  [n] just show me the guide: "
if errorlevel 2 goto guide
echo(
echo    Installing Codex... this can take a minute.
echo(
powershell -ExecutionPolicy ByPass -c "irm https://chatgpt.com/codex/install.ps1 | iex"
goto installed_reopen

:installed_reopen
echo(
echo    Installed! Please close this window and double-click again to start.
echo    (That just lets your computer see the newly installed app.)
echo(
pause
exit /b 0

:guide
echo(
echo    No problem. I'll open the official setup guide in your browser --
echo    it has the exact command to copy. Once it's installed, double-click here again.
start "" "%DOCS%"
echo(
pause
exit /b 0

:done
echo(
echo    All done! You can close this window. See you next time.
echo(
