#!/bin/bash
# ─────────────────────────────────────────────────────────────
# Talk to my files
# Double-click to chat with the AI about the files in this
# folder. No coding knowledge needed.
# (Generated by the agent-friendly-knowledge-docs skill.)
# ─────────────────────────────────────────────────────────────

# Enter the folder this file lives in (the "mother" folder).
cd "$(dirname "$0")" || exit 1

# Clear the screen so no scary technical text shows.
clear

# Calm colors, with a fallback if the terminal doesn't support them.
if [ -t 1 ]; then
  B=$'\033[1m'; DIM=$'\033[2m'; BLUE=$'\033[38;5;68m'; GREEN=$'\033[38;5;71m'; R=$'\033[0m'
else
  B=""; DIM=""; BLUE=""; GREEN=""; R=""
fi

printf '\n'
printf '   %s%sHi! 👋%s\n' "$B" "$BLUE" "$R"
printf '\n'
printf "   I'm the AI that knows the files in this folder.\n"
printf '   Ask me anything about them.\n'
printf '\n'
printf '   %sFor example:%s\n' "$DIM" "$R"
printf '   %s· "what'\''s in this folder?"%s\n' "$DIM" "$R"
printf '   %s· "summarize the proposal for client X"%s\n' "$DIM" "$R"
printf '   %s· "which is the latest version of the model?"%s\n' "$DIM" "$R"
printf '\n'
printf '   %s────────────────────────────────────────────%s\n' "$DIM" "$R"
printf '\n'

# Python powers the "what changed" check below. Offer to install it if missing;
# if declined or slow, just continue to the chat (tracking turns on later).
if ! command -v python3 >/dev/null 2>&1; then
  printf '   %sPython isn'\''t installed%s — it powers the automatic change-tracking.\n' "$B" "$R"
  printf '   Install it now?  %s[y]%s yes   /   %s[n]%s skip: ' "$B" "$R" "$B" "$R"
  read -r pyans
  printf '\n'
  case "$pyans" in
    y|Y|s|S|yes|sim)
      printf '   %sOpening the macOS installer for Python…%s click "Install" and let it run.\n' "$DIM" "$R"
      xcode-select --install 2>/dev/null || true
      printf '   %sWaiting for it to finish… Ctrl-C to skip and just chat.%s\n' "$DIM" "$R"
      tries=0
      until python3 --version >/dev/null 2>&1; do
        sleep 5; tries=$((tries + 1))
        [ $((tries % 12)) -eq 0 ] && printf '   %s…still installing…%s\n' "$DIM" "$R"
        [ "$tries" -ge 240 ] && break
      done
      command -v python3 >/dev/null 2>&1 && printf '   %s✓ Python is ready.%s\n\n' "$GREEN" "$R"
      ;;
    *) printf '   %sOK — chatting now; tracking turns on once Python is installed.%s\n\n' "$DIM" "$R" ;;
  esac
fi

# Forcing gate (works for Claude Code AND Codex): if the files changed since the
# docs were last updated, nudge the user to catch up first.
if [ -f ".claude/hooks/snapshot.py" ]; then
  python3 ".claude/hooks/snapshot.py" check . >/dev/null 2>&1
  if [ "$?" -eq 3 ]; then
    printf '   %s⚠  Some files changed since last time.%s\n' "$B" "$R"
    printf "   %sBefore anything else, ask me: \"what changed?\" — I'll update the notes.%s\n\n" "$DIM" "$R"
  fi
fi

have() { command -v "$1" >/dev/null 2>&1; }
have_claude=0; have claude && have_claude=1
have_codex=0;  have codex  && have_codex=1

status() {  # $1 = installed flag
  if [ "$1" -eq 1 ]; then
    printf '%s✓ installed%s' "$GREEN" "$R"
  else
    printf "%s— not installed, I can set it up%s" "$DIM" "$R"
  fi
}

# Always show the picker, marking what's installed.
printf '   %sWhich assistant do you want to use?%s\n\n' "$B" "$R"
printf '   %s[1]%s Claude Code   ' "$B" "$R"; status "$have_claude"; printf '\n'
printf '   %s[2]%s Codex         ' "$B" "$R"; status "$have_codex";  printf '\n\n'
printf '   Type 1 or 2 and press Enter: '
read -r choice
printf '\n'

case "$choice" in
  2) sel=codex;  name="Codex";       installed=$have_codex
     install_cmd='curl -fsSL https://chatgpt.com/codex/install.sh | sh'
     docs='https://learn.chatgpt.com/docs/codex/cli' ;;
  *) sel=claude; name="Claude Code"; installed=$have_claude
     install_cmd='curl -fsSL https://claude.ai/install.sh | bash'
     docs='https://code.claude.com/docs/en/quickstart' ;;
esac

launch() { if [ "$sel" = codex ]; then codex; else claude; fi; }

if [ "$installed" -eq 1 ]; then
  launch
else
  printf "   %s%s isn't installed yet.%s I can set it up for you, right here.\n" "$B" "$name" "$R"
  printf '   Install it now?  %s[y]%s yes   /   %s[n]%s no, just show me the steps: ' "$B" "$R" "$B" "$R"
  read -r ans
  printf '\n'
  case "$ans" in
    y|Y|s|S|yes|sim)
      printf '   %sInstalling %s… this can take a minute.%s\n\n' "$DIM" "$name" "$R"
      eval "$install_cmd"
      # Let this session see the freshly installed command.
      export PATH="$HOME/.local/bin:$HOME/bin:/usr/local/bin:$PATH"
      hash -r 2>/dev/null
      if have "$sel"; then
        printf '\n   %sInstalled!%s Opening it now — the first time, it will ask you to sign in.\n\n' "$GREEN" "$R"
        launch
      else
        printf '\n   %sInstalled!%s Please %sclose this window and double-click again%s to start.\n' "$GREEN" "$R" "$B" "$R"
        printf '   %s(That just lets your computer see the newly installed app.)%s\n\n' "$DIM" "$R"
        exit 0
      fi
      ;;
    *)
      printf '   No problem. Here are the steps:\n\n'
      printf '   1) Open the %sTerminal%s app.\n' "$B" "$R"
      printf '   2) Paste this line and press Enter:\n\n'
      printf '      %s%s%s\n\n' "$BLUE" "$install_cmd" "$R"
      printf '   3) When it finishes, come back and double-click here again.\n\n'
      printf "   I'll also open the official guide in your browser…\n\n"
      open "$docs" >/dev/null 2>&1
      exit 0
      ;;
  esac
fi

# Friendly goodbye when the conversation ends.
printf '\n   %sAll done! You can close this window. See you next time 👋%s\n\n' "$BLUE" "$R"
